// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Src.Infra.DataBase.SqlServer.Ef.DbContext;

#nullable disable

namespace Src.Infra.DataBase.SqlServer.Ef.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AppExpertSubCategory", b =>
                {
                    b.Property<int>("AppExpertsId")
                        .HasColumnType("int");

                    b.Property<int>("SpecialtiesId")
                        .HasColumnType("int");

                    b.HasKey("AppExpertsId", "SpecialtiesId");

                    b.HasIndex("SpecialtiesId");

                    b.ToTable("AppExpertSubCategory");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Customer",
                            NormalizedName = "CUSTOMER"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Expert",
                            NormalizedName = "EXPERT"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 2,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 3,
                            RoleId = 3
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Src.Domain.Core.AAM.ManageUser.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<float>("Balance")
                        .HasColumnType("real");

                    b.Property<string>("CardNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<int>("Province")
                        .HasColumnType("int");

                    b.Property<DateTime>("RegisterDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Src.Domain.Core.Base.Entities.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RequestId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RequestId");

                    b.ToTable("Image");
                });

            modelBuilder.Entity("Src.Domain.Core.Customer_Manager.Customer.Entities.AppRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("ExecutionDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("ExecutionTime")
                        .HasColumnType("time");

                    b.Property<int>("HomeServiceId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("HomeServiceId");

                    b.ToTable("Requests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CustomerId = 2,
                            Details = "نیاز به ترمیم ترک سقف خانه دارم.",
                            ExecutionDate = new DateOnly(2025, 2, 18),
                            ExecutionTime = new TimeOnly(16, 40, 0),
                            HomeServiceId = 2,
                            IsActive = true,
                            RequestDate = new DateTime(2025, 2, 16, 22, 2, 51, 510, DateTimeKind.Local).AddTicks(9637),
                            Status = 0
                        });
                });

            modelBuilder.Entity("Src.Domain.Core.Expert_Manager.Expert.Entities.FeedBack", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<int>("ExpertId")
                        .HasColumnType("int");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ExpertId");

                    b.ToTable("FeedBacks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CustomerId = 2,
                            Description = "کار خیلی عالی و سر وقت انجام شد",
                            ExpertId = 3,
                            Score = 5
                        });
                });

            modelBuilder.Entity("Src.Domain.Core.Expert_Manager.Expert.Entities.Proposal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("DueTime")
                        .HasColumnType("time");

                    b.Property<int>("ExpertId")
                        .HasColumnType("int");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<DateTime>("ProposalDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("RequestId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExpertId");

                    b.HasIndex("RequestId");

                    b.ToTable("Proposals");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "من میتوانم این کار را در زمان مقرر به اتمام برسانم",
                            DueDate = new DateOnly(2025, 2, 18),
                            DueTime = new TimeOnly(16, 40, 0),
                            ExpertId = 3,
                            Price = 350f,
                            ProposalDate = new DateTime(2025, 2, 16, 22, 2, 51, 510, DateTimeKind.Local).AddTicks(8711),
                            RequestId = 1,
                            Status = 0
                        });
                });

            modelBuilder.Entity("Src.Domain.Core.HomeServices_Manager.HomeServices.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImagePath = "Images/Categories/برق-کشی-1.jpg",
                            Title = "خدمات برق"
                        },
                        new
                        {
                            Id = 2,
                            ImagePath = "Images/Categories/نقاشی.jpg",
                            Title = "نقاشی ساختمان"
                        },
                        new
                        {
                            Id = 3,
                            ImagePath = "Images/Categories/تعمیر-لوازم-خانگی.jpg",
                            Title = "تعمیر لوازم خانه"
                        },
                        new
                        {
                            Id = 4,
                            ImagePath = "Images/Categories/بهداشت-و-نظافت.jpg",
                            Title = "خدمات نظافت"
                        },
                        new
                        {
                            Id = 5,
                            ImagePath = "Images/Categories/سمپاشی.jpg",
                            Title = "کنترل آفات"
                        },
                        new
                        {
                            Id = 6,
                            ImagePath = "Images/Categories/دکوراسیون-داخلی.jpg",
                            Title = "نو سازی ساختمان"
                        },
                        new
                        {
                            Id = 7,
                            ImagePath = "Images/Categories/تاسیسات-ساختمان.jpg",
                            Title = "تهویه هوا "
                        },
                        new
                        {
                            Id = 8,
                            ImagePath = "Images/Categories/لوله-کشی.jpg",
                            Title = "خدمات لوله کشی"
                        },
                        new
                        {
                            Id = 9,
                            ImagePath = "Images/Categories/ایمنی-و-امنیت-ساختمان.jpg",
                            Title = "امنیت ساختمان"
                        },
                        new
                        {
                            Id = 10,
                            ImagePath = "Images/Categories/نجاری.jpg",
                            Title = "نجاری"
                        },
                        new
                        {
                            Id = 11,
                            ImagePath = "Images/Categories/بنایی.jpg",
                            Title = "بنایی"
                        });
                });

            modelBuilder.Entity("Src.Domain.Core.HomeServices_Manager.HomeServices.Entities.HomeService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<float>("BasePrice")
                        .HasColumnType("real");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("SubCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("Views")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SubCategoryId");

                    b.ToTable("HomeServices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BasePrice = 400f,
                            Description = "ایزوله سازی سطوح سیمانی و جلوگیری از نفوذ اب و رطوبت به دیوار ها و کف.",
                            ImagePath = "اب بندی.jpg",
                            IsActive = true,
                            SubCategoryId = 24,
                            Title = "آب بندی",
                            Views = 1
                        },
                        new
                        {
                            Id = 2,
                            BasePrice = 300f,
                            Description = "ترمیم ترک های دیوار و سقف به منظور جلوگیری از اسیب های ناشی از نشست ساختمان یا رطوبت.",
                            ImagePath = "ترمیم ترک.jpg",
                            IsActive = true,
                            SubCategoryId = 22,
                            Title = "ترمیم ترک",
                            Views = 1
                        });
                });

            modelBuilder.Entity("Src.Domain.Core.HomeServices_Manager.HomeServices.Entities.SubCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("SubCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 4,
                            Name = "نظافت مسکونی"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 4,
                            Name = "نظافت اداری"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            Name = "تعمیرات و نگهدرای"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Name = "سرویس برق خانه"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 8,
                            Name = "نصب"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 8,
                            Name = "تعمیرات"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 6,
                            Name = "دکوراسیون داخلی"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 6,
                            Name = "نوسازی نمای ساختمان"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 7,
                            Name = "سیستم سرمایش"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 7,
                            Name = "سیستم گرمایش"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 5,
                            Name = "کنترل افت مسکونی"
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 5,
                            Name = "کنترل افت اداری"
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 2,
                            Name = "نقاشی داخل ساختمان"
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 2,
                            Name = "نقاشی نما"
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 2,
                            Name = "کاغذ دیواری"
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 9,
                            Name = "سیستم امنیتی هوشمند"
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 9,
                            Name = "سرویس قفل در"
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 9,
                            Name = "دوربین امنیتی"
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 3,
                            Name = "تعمیرات مبلمان"
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 10,
                            Name = "کابینت سازی"
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 10,
                            Name = "کف سازی و صافکاری چوب"
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 11,
                            Name = "گچ کاری"
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 11,
                            Name = "کاشی کاری"
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 11,
                            Name = "سیمان کاری"
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 1,
                            Name = "سرویس برق اضظراری"
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 1,
                            Name = "سرویس برق اداری"
                        });
                });

            modelBuilder.Entity("Src.Domain.Core.Payment_Manager.Payment.Entities.AppPayment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AdminId")
                        .HasColumnType("int");

                    b.Property<float>("Amount")
                        .HasColumnType("real");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("ExpertId")
                        .HasColumnType("int");

                    b.Property<int>("RequestId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ExpertId");

                    b.HasIndex("RequestId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("Src.Domain.Core.AAM.ManageAdmin.Entities.Admin", b =>
                {
                    b.HasBaseType("Src.Domain.Core.AAM.ManageUser.Entities.User");

                    b.ToTable("Admin", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            Balance = 0f,
                            CardNumber = "5057222213180000",
                            ConcurrencyStamp = "09da5277-0485-4946-8fe8-e115cd83d7c5",
                            Email = "rajabiarash36@gmail.com",
                            EmailConfirmed = false,
                            IsActive = true,
                            LockoutEnabled = true,
                            NormalizedEmail = "RAJABIARASH36@GMAIL.COM",
                            NormalizedUserName = "ARASH",
                            PasswordHash = "AQAAAAIAAYagAAAAEKgkBe5ACscTieKr1Hq+NLSELzylP7GMdADxFu0AikLYo1CkKW8JWFUOGoV91WJEIw==",
                            PhoneNumber = "09112789132",
                            PhoneNumberConfirmed = false,
                            Province = 1,
                            RegisterDate = new DateTime(2025, 2, 16, 22, 2, 51, 511, DateTimeKind.Local).AddTicks(2017),
                            SecurityStamp = "b505bb2c-3e7b-44a1-8eb4-b842165f0ddd",
                            TwoFactorEnabled = false,
                            UserName = "Arash"
                        });
                });

            modelBuilder.Entity("Src.Domain.Core.Customer_Manager.Customer.Entities.AppCustomer", b =>
                {
                    b.HasBaseType("Src.Domain.Core.AAM.ManageUser.Entities.User");

                    b.Property<string>("Address")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.ToTable("Customers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 2,
                            AccessFailedCount = 0,
                            Balance = 10000000f,
                            CardNumber = "5057222213181111",
                            ConcurrencyStamp = "13c51c2c-c9fe-467a-a94c-4d02d0056bec",
                            Email = "rajabiAshkan36@gmail.com",
                            EmailConfirmed = false,
                            IsActive = true,
                            LockoutEnabled = true,
                            NormalizedEmail = "RAJABIASHKAN36@GMAIL.COM",
                            NormalizedUserName = "ASHKAN",
                            PasswordHash = "AQAAAAIAAYagAAAAEPuiyWHQHwEd8LJLBLDWnLyvpY8cAGUol0kHjOh9jR4hL9FW8eMBIfu7JikurEiaLw==",
                            PhoneNumber = "09113889433",
                            PhoneNumberConfirmed = false,
                            Province = 1,
                            RegisterDate = new DateTime(2025, 2, 16, 22, 2, 51, 548, DateTimeKind.Local).AddTicks(5176),
                            SecurityStamp = "6061e228-7159-4401-a29f-08aeed68181f",
                            TwoFactorEnabled = false,
                            UserName = "Ashkan",
                            Address = "Gonbad-Kavoos"
                        });
                });

            modelBuilder.Entity("Src.Domain.Core.Expert_Manager.Expert.Entities.AppExpert", b =>
                {
                    b.HasBaseType("Src.Domain.Core.AAM.ManageUser.Entities.User");

                    b.Property<string>("Bioghraphy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WorkPlaceAddress")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.ToTable("Experts", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 3,
                            AccessFailedCount = 0,
                            Balance = 10000000f,
                            CardNumber = "5057222213182222",
                            ConcurrencyStamp = "f740aba4-087a-4748-b180-28bd1e932bd7",
                            Email = "moharerymahmood36@gmail.com",
                            EmailConfirmed = false,
                            IsActive = true,
                            LockoutEnabled = true,
                            NormalizedEmail = "MOHARERYMAHMOOD36@GMAIL.COM",
                            NormalizedUserName = "MAHMOOD",
                            PasswordHash = "AQAAAAIAAYagAAAAEJfWaYV/Mwc/tCy0rZUtqh0zCEksl4w1aD333c3nBFmhvBNsdAHBZacbomzIZc+Tmw==",
                            PhoneNumber = "09334569433",
                            PhoneNumberConfirmed = false,
                            Province = 7,
                            RegisterDate = new DateTime(2025, 2, 16, 22, 2, 51, 584, DateTimeKind.Local).AddTicks(3844),
                            SecurityStamp = "9c304176-d022-4f75-846c-0c65f0b00ee2",
                            TwoFactorEnabled = false,
                            UserName = "Mahmood",
                            WorkPlaceAddress = "عظیمیه-میدان اسبی-پارک"
                        });
                });

            modelBuilder.Entity("AppExpertSubCategory", b =>
                {
                    b.HasOne("Src.Domain.Core.Expert_Manager.Expert.Entities.AppExpert", null)
                        .WithMany()
                        .HasForeignKey("AppExpertsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Src.Domain.Core.HomeServices_Manager.HomeServices.Entities.SubCategory", null)
                        .WithMany()
                        .HasForeignKey("SpecialtiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("Src.Domain.Core.AAM.ManageUser.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("Src.Domain.Core.AAM.ManageUser.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Src.Domain.Core.AAM.ManageUser.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("Src.Domain.Core.AAM.ManageUser.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Src.Domain.Core.Base.Entities.Image", b =>
                {
                    b.HasOne("Src.Domain.Core.Customer_Manager.Customer.Entities.AppRequest", "Request")
                        .WithMany("Images")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Request");
                });

            modelBuilder.Entity("Src.Domain.Core.Customer_Manager.Customer.Entities.AppRequest", b =>
                {
                    b.HasOne("Src.Domain.Core.Customer_Manager.Customer.Entities.AppCustomer", "Customer")
                        .WithMany("Requests")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Src.Domain.Core.HomeServices_Manager.HomeServices.Entities.HomeService", "HomeService")
                        .WithMany("Requests")
                        .HasForeignKey("HomeServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("HomeService");
                });

            modelBuilder.Entity("Src.Domain.Core.Expert_Manager.Expert.Entities.FeedBack", b =>
                {
                    b.HasOne("Src.Domain.Core.Customer_Manager.Customer.Entities.AppCustomer", "Customer")
                        .WithMany("FeedBacks")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Src.Domain.Core.Expert_Manager.Expert.Entities.AppExpert", "Expert")
                        .WithMany("FeedBacks")
                        .HasForeignKey("ExpertId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Expert");
                });

            modelBuilder.Entity("Src.Domain.Core.Expert_Manager.Expert.Entities.Proposal", b =>
                {
                    b.HasOne("Src.Domain.Core.Expert_Manager.Expert.Entities.AppExpert", "Expert")
                        .WithMany("Proposals")
                        .HasForeignKey("ExpertId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Src.Domain.Core.Customer_Manager.Customer.Entities.AppRequest", "Request")
                        .WithMany("Proposals")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Expert");

                    b.Navigation("Request");
                });

            modelBuilder.Entity("Src.Domain.Core.HomeServices_Manager.HomeServices.Entities.HomeService", b =>
                {
                    b.HasOne("Src.Domain.Core.HomeServices_Manager.HomeServices.Entities.SubCategory", "SubCategory")
                        .WithMany("HomeServices")
                        .HasForeignKey("SubCategoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("SubCategory");
                });

            modelBuilder.Entity("Src.Domain.Core.HomeServices_Manager.HomeServices.Entities.SubCategory", b =>
                {
                    b.HasOne("Src.Domain.Core.HomeServices_Manager.HomeServices.Entities.Category", "Category")
                        .WithMany("SubCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Src.Domain.Core.Payment_Manager.Payment.Entities.AppPayment", b =>
                {
                    b.HasOne("Src.Domain.Core.AAM.ManageAdmin.Entities.Admin", "Admin")
                        .WithMany("Payments")
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Src.Domain.Core.Customer_Manager.Customer.Entities.AppCustomer", "Customer")
                        .WithMany("Payments")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Src.Domain.Core.Expert_Manager.Expert.Entities.AppExpert", "Expert")
                        .WithMany("Payments")
                        .HasForeignKey("ExpertId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Src.Domain.Core.Customer_Manager.Customer.Entities.AppRequest", "Request")
                        .WithMany()
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Admin");

                    b.Navigation("Customer");

                    b.Navigation("Expert");

                    b.Navigation("Request");
                });

            modelBuilder.Entity("Src.Domain.Core.AAM.ManageAdmin.Entities.Admin", b =>
                {
                    b.HasOne("Src.Domain.Core.AAM.ManageUser.Entities.User", null)
                        .WithOne()
                        .HasForeignKey("Src.Domain.Core.AAM.ManageAdmin.Entities.Admin", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Src.Domain.Core.Customer_Manager.Customer.Entities.AppCustomer", b =>
                {
                    b.HasOne("Src.Domain.Core.AAM.ManageUser.Entities.User", null)
                        .WithOne()
                        .HasForeignKey("Src.Domain.Core.Customer_Manager.Customer.Entities.AppCustomer", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Src.Domain.Core.Expert_Manager.Expert.Entities.AppExpert", b =>
                {
                    b.HasOne("Src.Domain.Core.AAM.ManageUser.Entities.User", null)
                        .WithOne()
                        .HasForeignKey("Src.Domain.Core.Expert_Manager.Expert.Entities.AppExpert", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Src.Domain.Core.Customer_Manager.Customer.Entities.AppRequest", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("Proposals");
                });

            modelBuilder.Entity("Src.Domain.Core.HomeServices_Manager.HomeServices.Entities.Category", b =>
                {
                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("Src.Domain.Core.HomeServices_Manager.HomeServices.Entities.HomeService", b =>
                {
                    b.Navigation("Requests");
                });

            modelBuilder.Entity("Src.Domain.Core.HomeServices_Manager.HomeServices.Entities.SubCategory", b =>
                {
                    b.Navigation("HomeServices");
                });

            modelBuilder.Entity("Src.Domain.Core.AAM.ManageAdmin.Entities.Admin", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("Src.Domain.Core.Customer_Manager.Customer.Entities.AppCustomer", b =>
                {
                    b.Navigation("FeedBacks");

                    b.Navigation("Payments");

                    b.Navigation("Requests");
                });

            modelBuilder.Entity("Src.Domain.Core.Expert_Manager.Expert.Entities.AppExpert", b =>
                {
                    b.Navigation("FeedBacks");

                    b.Navigation("Payments");

                    b.Navigation("Proposals");
                });
#pragma warning restore 612, 618
        }
    }
}
